# typed: strict
# frozen_string_literal: true

# This file was generated by the GitHub Account Switcher release workflow. DO NOT EDIT.
cask "github-account-switcher" do
  version "1.0.0"
  sha256 "394450a6a7c30e566c0090c934697dbbefa136ff03e92b886c1913eca764c48f"

  url "https://github.com/mobilepur/github-account-switcher/releases/download/v#{version}/GitHub-Account-Switcher.tar.gz"
  name "GitHub Account Switcher"
  desc "Switch GitHub CLI accounts and SSH identities from the menu bar"
  homepage "https://github.com/mobilepur/github-account-switcher"

  depends_on formula: "gh"
  depends_on macos: :sonoma

  app "GitHub Account Switcher.app"
  binary "gh-switcher"

  postflight do
    [
      "#{appdir}/GitHub Account Switcher.app",
      "#{staged_path}/gh-switcher",
    ].each do |path|
      quarantine = system_command(
        "/usr/bin/xattr",
        args:         ["-p", "com.apple.quarantine", path],
        must_succeed: false,
        print_stderr: false,
      )
      next unless quarantine&.success?

      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", path]
    end
  end
end
