# This file was generated by GoReleaser. DO NOT EDIT.
cask "xlocal" do
  version "0.3.0"

  on_macos do
    sha256 "40db960f8e2699b5efe73032880468cc15a65055b00dd827dc3d37953c332338"
    url "https://github.com/mobilepur/xlocal/releases/download/v#{version}/xlocal_#{version}_darwin_all.tar.gz"
  end

  name "xlocal"
  desc "Translate missing strings in Xcode String Catalogs using the Anthropic API"
  homepage "https://github.com/MobilePur/xlocal"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "xlocal"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/xlocal"]
    end
  end

  # No zap stanza required

end
