# This file was generated by GoReleaser. DO NOT EDIT.
cask "xlocal" do
  version "0.8.1"

  on_macos do
    sha256 "17def766b4f28d9a2433ca8ebf4a8b2cfb415ea47c581b5fe13c05c1723346c8"
    url "https://github.com/mobilepur/xlocal/releases/download/v#{version}/xlocal_#{version}_darwin_all.tar.gz"
  end

  name "xlocal"
  desc "Translate missing strings in Xcode catalogs and Android XML using the Anthropic API"
  homepage "https://github.com/MobilePur/xlocal"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "xlocal"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/xlocal"]
    end
  end

  # No zap stanza required

end
