# typed: strict
# frozen_string_literal: true

# This file was generated by the XPlay release workflow. DO NOT EDIT.
cask "xplay" do
  version "1.0.0"
  sha256 "69b589f78313489733f61cd5ca431d56e3c96247fd43f7ce2466b3f9f6cd3430"

  url "https://github.com/mobilepur/xplay/releases/download/v#{version}/XPlay.tar.gz"
  name "XPlay"
  desc "Build and launch Xcode projects from the menu bar"
  homepage "https://github.com/mobilepur/xplay"

  depends_on macos: :sequoia

  app "XPlay.app"

  postflight do
    path = "#{appdir}/XPlay.app"
    quarantine = system_command(
      "/usr/bin/xattr",
      args:         ["-p", "com.apple.quarantine", path],
      must_succeed: false,
      print_stderr: false,
    )
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", path] if quarantine&.success?
  end

  uninstall quit: "de.mobilepur.XPlay"

  zap trash: [
    "~/Library/Caches/XPlay",
    "~/Library/Preferences/de.mobilepur.XPlay.plist",
    "~/Library/Saved Application State/de.mobilepur.XPlay.savedState",
  ]

  caveats "XPlay requires a full Xcode installation to build projects and run simulators."
end
