# typed: strict
# frozen_string_literal: true

# This file was generated by the XPlay release workflow. DO NOT EDIT.
cask "xplay" do
  version "1.0.1"
  sha256 "f0103b8e63ee3b6a2d7de6cc87c3f40818f2744c29e195ccbde226a1e924a5f4"

  url "https://github.com/mobilepur/xplay/releases/download/v#{version}/XPlay.tar.gz"
  name "XPlay"
  desc "Build and launch Xcode projects from the menu bar"
  homepage "https://github.com/mobilepur/xplay"

  depends_on macos: :sequoia

  app "XPlay.app"

  postflight_steps do
    run "/usr/bin/xattr",
        args:         ["-dr", "com.apple.quarantine", "{{appdir}}/XPlay.app"],
        must_succeed: false,
        print_stderr: false
  end

  uninstall quit: "de.mobilepur.XPlay"

  zap trash: [
    "~/Library/Caches/XPlay",
    "~/Library/Preferences/de.mobilepur.XPlay.plist",
    "~/Library/Saved Application State/de.mobilepur.XPlay.savedState",
  ]

  caveats "XPlay requires a full Xcode installation to build projects and run simulators."
end
